//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientReviewScore
    {
        public int ClientReviewScoreId { get; set; }
        public int ClientId { get; set; }
        public int PositiveReview { get; set; }
        public int NegativeReview { get; set; }
        public int NeutralReview { get; set; }
        public System.DateTime OrderDate { get; set; }
    }
}
