//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientAddress1
    {
        public int AddressId { get; set; }
        public int ClientId { get; set; }
        public string Address { get; set; }
        public string Apt_suite { get; set; }
        public int CityId { get; set; }
        public int RegionId { get; set; }
        public int CountryId { get; set; }
        public string ZipCode { get; set; }
        public string PhoneNumber { get; set; }
        public string Cross_Stree { get; set; }
        public string Instructions { get; set; }
        public int AddressTypeId { get; set; }
    }
}
