//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    public partial class CookerCuisine
    {
        public int CookerCuisineId { get; set; }
        public int CuisineTypeId { get; set; }
        public int CookerId { get; set; }
    }
}
