//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CookerPaymentMethod
    {
        public int CookerPaymentMethodId { get; set; }
        public int PaymentMethodId { get; set; }
        public int CookerId { get; set; }
    }
}
