//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace Model
{
    public partial class CookerHoursofOperation
    {
        public int CookerId { get; set; }
        public Nullable<TimeSpan> OpeningHours { get; set; }
        public Nullable<TimeSpan> ClosingHours { get; set; }
        public string OpeningDays { get; set; }
        public Nullable<TimeSpan> DeliveryHours { get; set; }
        public Nullable<TimeSpan> ClosingDeliveryHours { get; set; }
        public string DeliveryDays { get; set; }
        public Nullable<TimeSpan> PickUpHours { get; set; }
        public Nullable<TimeSpan> ClosingPickUpHours { get; set; }
        public string PickUpDays { get; set; }
    }
}
