//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace Model
{
    public partial class CookerCoupon
    {
        public int CookerCouponId { get; set; }
        public int CookerId { get; set; }
        public int CouponId { get; set; }
        public DateTime CouponDate { get; set; }
    }
}
