//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    public partial class CookerReviewServiceDetail
    {
        public int CookerReviewServiceDetailId { get; set; }
        public int CookerId { get; set; }
        public int ItemAccuracyRating { get; set; }
        public int CommunicationRating { get; set; }
        public int DeliveryTimeRating { get; set; }
        public int OverallFeedBackRating { get; set; }
        public int NumberofRatings { get; set; }
    }
}
