//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    public partial class DeliveryZone
    {
        public int DeliveryId { get; set; }
        public string DeliveryName { get; set; }
        public decimal MinimumOrder { get; set; }
        public int CurrencyId { get; set; }
        public decimal DeliveryFees { get; set; }
    }
}
