//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dish
    {
        public int DishId { get; set; }
        public int MenuId { get; set; }
        public int CookerId { get; set; }
        public string SectionTitle { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public decimal Price { get; set; }
        public string Photo { get; set; }
        public int ServingId { get; set; }
        public string SpecialNote { get; set; }
        public int CurrencyId { get; set; }
    }
}
