//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class FeedBack
    {
        public int FeedbackId { get; set; }
        public int OrderId { get; set; }
        public int RatingCodeId { get; set; }
        public System.DateTime FeedBackDateTime { get; set; }
        public int ReviewId { get; set; }
    }
}
