//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class IndustryAverageRating
    {
        public int IndustryAverageRatingId { get; set; }
        public decimal ItemAccuracyIndustryAverageRating { get; set; }
        public decimal CommunicationIndustryAverageRating { get; set; }
        public decimal DeliveryTimeIndustryAverageRating { get; set; }
        public decimal OverallFeedBackIndustryAverageRating { get; set; }
    }
}
