//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice
    {
        public int InvoiceId { get; set; }
        public Nullable<int> OrderId { get; set; }
        public int ClientId { get; set; }
        public int CookerId { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
        public string OrderTypeValue { get; set; }
        public string PaymentMethodValue { get; set; }
        public string PromotionTitle { get; set; }
        public Nullable<decimal> PromotionPrice { get; set; }
        public Nullable<int> PromotionCurrencyId { get; set; }
        public string CouponTitle { get; set; }
        public Nullable<decimal> CouponPrice { get; set; }
        public Nullable<int> CouponCurrencyId { get; set; }
        public string PlanTitle { get; set; }
        public Nullable<decimal> SalesTax { get; set; }
        public Nullable<decimal> DeliveryFees { get; set; }
        public decimal SubTotal { get; set; }
        public decimal Total { get; set; }
        public int CurrencyId { get; set; }
        public int OrderModelTypeId { get; set; }
        public Nullable<int> CookerSubscriptionId { get; set; }
        public Nullable<int> ServingPriceId { get; set; }
        public Nullable<int> PlanId { get; set; }
        public Nullable<int> ClientSubscriptionId { get; set; }
        public Nullable<System.DateTime> SubscriptionStartDate { get; set; }
        public Nullable<System.DateTime> SubscriptionEndDate { get; set; }
        public Nullable<System.DateTime> SubscriptionInvoiceDate { get; set; }
    }
}
