//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderSubscription
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OrderSubscription()
        {
            this.OrderSubscriptionItems = new HashSet<OrderSubscriptionItem>();
        }
    
        public int OrderSubscriptionId { get; set; }
        public int ClientId { get; set; }
        public System.DateTime OrderDate { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
        public int OrderTypeId { get; set; }
        public int PaymentMethodId { get; set; }
        public Nullable<int> PromotionId { get; set; }
        public Nullable<int> CouponId { get; set; }
        public Nullable<int> PlanId { get; set; }
        public decimal SubTotal { get; set; }
        public int CurrencyId { get; set; }
        public int OrderStatusId { get; set; }
        public int ServingMeasurementId { get; set; }
        public int NumberofServingTotal { get; set; }
        public int ClientSubscriptionId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderSubscriptionItem> OrderSubscriptionItems { get; set; }
    }
}
