//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderToReview
    {
        public int ReviewId { get; set; }
        public int CookerId { get; set; }
        public int MenuId { get; set; }
        public string Comment { get; set; }
        public int OrderId { get; set; }
        public int ClientId { get; set; }
        public int UserTypeId { get; set; }
        public string PhotoFeedBack { get; set; }
        public int RatingId { get; set; }
        public int OverallRatingId { get; set; }
        public int ItemAccuracyRatingId { get; set; }
        public int CommunicationRatingId { get; set; }
        public int DeliveryTimeRatingId { get; set; }
        public int OverallFeedBackRatingId { get; set; }
    }
}
