//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentsHistory
    {
        public int PaymentHistoryId { get; set; }
        public int InvoiceId { get; set; }
        public int OrderId { get; set; }
        public int ClientId { get; set; }
        public int CookerId { get; set; }
        public string TransactionId { get; set; }
        public System.DateTime PaymentDate { get; set; }
        public decimal PaymentAmount { get; set; }
    }
}
