//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    public partial class Plan
    {
        public int PlanId { get; set; }
        public string ExternalId { get; set; }
        public string Description { get; set; }
        public string Title { get; set; }
    }
}
