//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Refund
    {
        public int RefundId { get; set; }
        public int OrderDetailId { get; set; }
        public int RefundTypeId { get; set; }
        public System.DateTime DisputeDate { get; set; }
        public decimal RefundAmount { get; set; }
        public int StatusId { get; set; }
        public int ReasonId { get; set; }
        public string Evidence { get; set; }
        public string Description { get; set; }
    }
}
