//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace Model
{
    public partial class Refund
    {
        public int RefundId { get; set; }
        public string TransactionID { get; set; }
        public int OrderId { get; set; }
        public int OrderModelTypeId { get; set; }
        public int ClientId { get; set; }
        public int CookerId { get; set; }
        public DateTime RefundDate { get; set; }
        public decimal RefundAmount { get; set; }
        public int StatusId { get; set; }
        public int ReasonId { get; set; }
        public string EvidencePhoto { get; set; }
        public string Description { get; set; }
    }
}
